name: Build Step

on:
  push:
    branches: ["main"]

jobs:  
  build-and-push-docker:
    name: Buiild Docker Image and Push to Docker Repository

    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout Stage
        uses: actions/checkout@v3
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: ammarhaiderak/fabstir-db:${{steps.vars.outputs.sha_short}}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  update-manifest:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker']
    env:
      GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ammarhaiderak/gitops-fabstir
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: Setup Git Config
        run: |
          git config user.email "ammarkhaliq@gmail.com"
          git config user.name "Ammar Haider"
          short_sha=$(git rev-parse --short HEAD)
          sed -i "s#ammarhaiderak.*#ammarhaiderak/fabstir-db:${short_sha}#g" fabstirdb/deployment.yaml
          git add -A
          git commit -am "Update image for ${short_sha}"
      - name: Pushing Updated Image Tag
        run: |
          export GITHUB_TOKEN=${{ secrets.G_TOKEN }}
          git push origin main
          
